### ISSUE TITLE
Isolation Forest converter

### ISSUE THREAD

**Issue by sv-youn** [onnx/sklearn-onnx#518] opened 2020-08-07 02:18 UTC
Could you please implement the converter for Isolation Forest? This algorithm is very good for anomaly detection. Thanks.

**Comment by xadupre** [comment] 2020-08-07 13:41
The PR #492 has not yet been merged but it is done. I'll close that issue as it is a duplicate of #234.

**Closed by xadupre** 2020-08-07 13:41 UTC
Labels: duplicate
